-- LA SIGNÉ CMS INLINE V22
-- Execute no SQL Editor do Supabase antes de ativar o CMS em produção.

create table if not exists public.site_state (
  id text primary key,
  draft jsonb not null default '{}'::jsonb,
  published jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  published_at timestamptz
);

create table if not exists public.content_versions (
  id bigint generated by default as identity primary key,
  site_id text not null,
  snapshot jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.site_state enable row level security;
alter table public.content_versions enable row level security;

revoke all on table public.site_state from anon, authenticated;
revoke all on table public.content_versions from anon, authenticated;
grant select, insert, update, delete on table public.site_state to service_role;
grant select, insert, update, delete on table public.content_versions to service_role;
grant usage, select on all sequences in schema public to service_role;

insert into public.site_state (id,draft,published)
values ('home','{}'::jsonb,'{}'::jsonb)
on conflict (id) do nothing;

-- Storage:
-- Crie no Dashboard > Storage um bucket PUBLIC chamado: site-media
-- Os uploads são assinados pelo backend da Vercel; a secret key nunca vai para o navegador.
