const frame=document.getElementById('siteFrame'),shell=document.getElementById('frameShell'),login=document.getElementById('login'),pw=document.getElementById('password');
const LOCAL=location.protocol==='file:'||location.hostname==='localhost'||location.hostname==='127.0.0.1';const LOCAL_PAGE=location.pathname.endsWith('/admin.html')?'index.html':'../index.html';let latestState=null;
function toast(m){const t=document.getElementById('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
async function authCheck(){if(LOCAL)return true;try{const r=await fetch('/api/auth',{credentials:'include'});return r.ok}catch(e){return false}}
async function init(){if(!(await authCheck()))login.classList.add('show');frame.src=LOCAL?LOCAL_PAGE+'?cms_edit=1':'/?cms_edit=1'}
window.addEventListener('message',e=>{if(e.data?.type==='LASIGNE_EDITOR_STATE')latestState=e.data.state});
document.querySelectorAll('.device').forEach(b=>b.onclick=()=>{document.querySelectorAll('.device').forEach(x=>x.classList.remove('active'));b.classList.add('active');shell.className='frame '+(b.dataset.device==='desktop'?'':b.dataset.device)});
document.getElementById('loginBtn').onclick=async()=>{const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:pw.value}),credentials:'include'});if(r.ok){login.classList.remove('show');frame.src='/?cms_edit=1';toast('Acesso liberado.')}else toast('Senha inválida.')};
document.getElementById('saveBtn').onclick=async()=>{if(!latestState){toast('Ainda carregando o estado da página.');return}if(LOCAL){localStorage.setItem('lasigne.cms.inline.draft.v22',JSON.stringify(latestState));frame.contentWindow.postMessage({type:'LASIGNE_SAVE_LOCAL'},'*');toast('Rascunho salvo neste navegador.');return}const r=await fetch('/api/state',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'save',state:latestState})});toast(r.ok?'Rascunho salvo no Supabase.':'Não foi possível salvar.');};
document.getElementById('publishBtn').onclick=async()=>{if(LOCAL){if(!latestState)return;frame.contentWindow.postMessage({type:'LASIGNE_PUBLISH_LOCAL'},'*');toast('Publicação local simulada. No domínio, publicar usa Supabase.');return}if(!confirm('Publicar este rascunho no site?'))return;const r=await fetch('/api/state',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'publish'})});toast(r.ok?'Publicado. A página pública já pode ler a nova versão.':'Falha ao publicar.');};
document.getElementById('resetBtn').onclick=()=>{if(confirm('Recarregar o rascunho salvo e descartar mudanças ainda não salvas?'))frame.src=(LOCAL?LOCAL_PAGE:'/')+'?cms_edit=1&t='+Date.now()};
document.getElementById('logoutBtn').onclick=async()=>{if(LOCAL){toast('Modo local não usa login.');return}await fetch('/api/logout',{method:'POST',credentials:'include'});location.reload()};
init();